# Generated by Django 3.1.1 on 2021-01-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_points',
            field=models.IntegerField(default=0),
        ),
    ]
