# Generated by Django 3.0.5 on 2021-01-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_pk', models.IntegerField(default=0)),
                ('team2_pk', models.IntegerField(default=0)),
            ],
        ),
    ]
